name: docs-content-link-rewrites-e2e

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string
        description: 'example: "hashicorp"'
      repo-name:
        required: true
        type: string
        description: 'example: "waypoint"'
      commit-sha:
        required: true
        type: string
        description: 'example: "github.sha"'
      main-branch-preview-url:
        required: true
        type: string
        description: 'example: "https://waypoint-git-main-hashicorp.vercel.app/"'
      pr-branch-preview-url:
        required: true
        type: string
        description: 'example: "https://waypoint-git-docs-ambmigrate-link-formats-hashicorp.vercel.app/"'

jobs:
  docs-content-link-rewrites-e2e:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ inputs.repo-owner }}
      REPO: ${{ inputs.repo-name }}
      COMMIT_SHA: ${{ inputs.commit-sha }}
      MAIN_BRANCH_PREVIEW_URL: ${{ inputs.main-branch-preview-url }}
      PR_BRANCH_PREVIEW_URL: ${{ inputs.pr-branch-preview-url }}
    steps:
      - name: Determine if the workflow should run
        id: should-run-for-branch
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: process.env.OWNER,
              repo: process.env.REPO,
              commit_sha: process.env.COMMIT_SHA
            })
            return data && data[0].head.ref === "docs/amb.migrate-link-formats"

      # @TODO remove `ref` setting before merging
      - name: Check out dev-portal repo
        uses: actions/checkout@v3
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        with:
          repository: hashicorp/dev-portal
          path: dev-portal
          ref: amb.link-rewrites-e2e-tests

      - name: Change into cloned dev-portal directory
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        run: cd dev-portal

      - name: Install dev-portal deps
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        run: npm ci

      - name: Install Playwright
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        run: npx playwright install --with-deps

      - name: Load data for e2e tests
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        run: npm run test:e2e:linkRewrites:loadData

      - name: Run e2e tests
        if: ${{ steps.should-run-for-branch.outputs.result == 'true' }}
        run: npm run test:e2e:linkRewrites
